### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/shogun-cpp-feedstock#1]
Note that shogun uses C++11 and doesn't compile 32-bit, so this is only going to be possible for win-64, python 3.5+.

Issues:

- [x] `bigobj` compile error: fixed in https://github.com/shogun-toolbox/shogun/commit/72cfeb15639d4b39565d61700dce11c0d839c4da, add as patch if for 6.0.0
- [x] `algorithm` header missing: fixed in https://github.com/shogun-toolbox/shogun/commit/8bf4aed8252e1c3772d249eb8b854de3286dc2e0, add as patch if for 6.0.0
- [ ] Not linking the examples correctly when there are optional shared libraries present: https://github.com/shogun-toolbox/shogun/issues/3917
- [ ] Even with the shared lib dependencies turned off, AppVeyor [ran out of space](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.14895/job/j7175cu857satqxa); probably need to talk to them about that
- [ ] BLAS/LAPACK support: not a huge deal because it mostly uses Eigen
  - MKL option: depends on https://github.com/conda-forge/staged-recipes/issues/3022, and would probably also need to distribute the future [BSD version of shogun](https://github.com/shogun-toolbox/shogun/projects/7)
  - Another: OpenBLAS, depending on https://github.com/conda-forge/openblas-feedstock/issues/2

**Comment by vigsterkr** [comment]
@dougalsutherland i've just pushed couple of fixes to develop that should actually fix all the issues regarding windows build. i've used anaconda on windows for the dependencies of shogun, and both mkl is detected and now the examples compile fine. so i reckon in the next release of shogun we could add the windows support.

**Comment by djsutherland** [comment]
Awesome. Eagerly awaiting the next release.

Unfortunately I don't think we can legally distribute an MKL-linked GPL version of Shogun, so that will have to wait for the BSD version. But conda-forge can't compile with MKL yet anyway, so not a big issue until that gets worked out anyway. :)

**Comment by vigsterkr** [comment]
mmm i guess then there's just no lapack/blas backend for windows version till then :)
