### ISSUE TITLE
USE_SWIG_DIRECTORS is turned off

### ISSUE THREAD

**Issue by vigsterkr** [conda-forge/shogun-cpp-feedstock#15]
i really dont understand why (as `USE_SWIG_DIRECTORS` is on by default) in the `shogun-cpp` release of conda-forge that flag is turned off:
```
grep DIR /opt/conda/include/shogun/lib/config.h
/* #undef USE_SWIG_DIRECTORS */
```

@dougalsutherland do you have any idea how this could have happend? :)

**Comment by djsutherland** [comment]
I definitely didn't turn it off, lol. Flags used are: https://github.com/conda-forge/shogun-cpp-feedstock/blob/3f5f301c07c6ff7e6971e2279e835eeb7b95cbf0/recipe/meta.yaml#L49-L59.

**Comment by djsutherland** [comment]
Oh, but swig isn't installed when we're building shogun-cpp. Should it be?

**Comment by djsutherland** [comment]
Added in 21f851b.

**Comment by vigsterkr** [comment]
swig isn't a problem... if you are rebuilding shogun-cpp could you add this cmake flag explicitly `-DUSE_SWIG_DIRECTORS=ON`
