### ISSUE TITLE
Add MKL variant

### ISSUE THREAD

**Issue by djsutherland** [conda-forge/shogun-cpp-feedstock#23]
https://github.com/conda-forge/staged-recipes/pull/6715

cc @vigsterkr

**Comment by djsutherland** [comment]
I think, though am not 100% clear, that legally we need to not distribute the GPL components when we're linking against MKL.

**Comment by vigsterkr** [comment]
@dougalsutherland there's yet another reason why it should be a separate formula

**Comment by vigsterkr** [comment]
as we can just disable the GPL part with `LICENSE_GPL_SHOGUN=OFF`

**Comment by djsutherland** [comment]
We can do that as part of the variant too.

**Comment by vigsterkr** [comment]
can be closed, fixed in https://github.com/conda-forge/shogun-cpp-feedstock/pull/34
